[build]
  publish = "."
  
[[redirects]]
  from = "/games/*"
  to = "/games/:splat.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/action"
  to = "/games/action.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/sports"
  to = "/games/sports.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/shooter"
  to = "/games/shooter.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/puzzle"
  to = "/games/puzzle.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/fighting"
  to = "/games/fighting.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/racing"
  to = "/games/racing.html"
  status = 200
  force = true

[[redirects]]
  from = "/games/anime"
  to = "/games/anime.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specify a custom header for HTML files to ensure proper content type
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html"
    Access-Control-Allow-Origin = "*" 